export const MILESTONES = [
  "Orientation Briefing",
  "Mission Alignment",
  "Values Assessment",
  "Foundations of Leadership",
  "Community Engagement I",
  "Civic Duty Overview",
  "Policy Analysis I",
  "Strategic Communication",
  "Conflict Resolution",
  "Network Building",
  "Public Speaking Mastery",
  "Resource Allocation",
  "Crisis Management",
  "Policy Analysis II",
  "Data-Driven Decisions",
  "Advocacy Fundamentals",
  "Grassroots Campaigning",
  "Media Relations",
  "Ethics in Leadership",
  "Community Engagement II",
  "Negotiation Tactics",
  "Financial Stewardship",
  "Team Dynamics",
  "Project Management",
  "Digital Strategy",
  "Legal Frameworks",
  "Cultural Competency",
  "Policy Analysis III",
  "Visionary Planning",
  "Stakeholder Management",
  "Impact Measurement",
  "Adaptive Leadership",
  "Coalition Building",
  "Systems Thinking",
  "Public Trust",
  "Innovation in Governance",
  "Resilience Training",
  "Mentorship Practicum",
  "Global Perspectives",
  "Civic Tech Integration",
  "Advanced Strategy",
  "Policy Capstone",
  "Leadership Summit",
  "Initiative Launch",
  "Final Victory"
];
