import { lazy, Suspense, ReactNode, useEffect } from "react";
import { Switch, Route, Router as WouterRouter } from "wouter";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";
import NotFound from "@/pages/not-found";
import { TelegramProvider, useTelegram } from "@/lib/telegram";
import { ErrorBoundary } from "@/components/error-boundary";
import { ModelLoadingFallback } from "@/components/model-loading-fallback";
import { DevModelSwitcher } from "@/components/dev-model-switcher";
import Splash from "@/pages/splash";
import Onboarding from "@/pages/onboarding";
import NativeLoginScreen from "@/pages/NativeLoginScreen";
import { apiFetch } from "@/lib/api";

import { ACTIVE_MODEL } from "@/config/model";

const DashboardComponent =
  ACTIVE_MODEL === "MODEL_2"
    ? lazy(() => import("@/pages/dashboard-model2"))
    : lazy(() => import("@/pages/dashboard"));

console.log(`[ALI] Active model: ${ACTIVE_MODEL}`);

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 2,
      retryDelay: (attempt) => Math.min(800 * Math.pow(2, attempt), 8_000),
      staleTime: 180_000,
      gcTime: 600_000,
      refetchOnWindowFocus: false,
    },
  },
});

function Router() {
  return (
    <Suspense fallback={<ModelLoadingFallback />}>
      <Switch>
        <Route path="/" component={Splash} />
        <Route path="/onboarding" component={Onboarding} />
        <Route path="/dashboard" component={DashboardComponent} />
        <Route component={NotFound} />
      </Switch>
    </Suspense>
  );
}

/**
 * In native (Capacitor) context, show the login screen until the user has
 * authenticated via a one-time code from the Telegram bot. In Telegram and
 * dev/browser contexts this gate is transparent.
 *
 * Also handles deep links: com.ali.digitalgateway://auth?code=XXXXXXXX
 * — generated by the bot's "Download Android" flow — for auto-login on
 * first launch after APK installation.
 */
function NativeAuthGate({ children }: { children: ReactNode }) {
  const { isNativeMode, isAuthenticated, loginNative } = useTelegram();

  useEffect(() => {
    if (!isNativeMode || isAuthenticated) return;

    async function handleUrl(url: string) {
      try {
        // Parse: com.ali.digitalgateway://auth?code=XXXXXXXX
        const parsed = new URL(url);
        if (
          parsed.protocol !== "com.ali.digitalgateway:" ||
          parsed.hostname !== "auth"
        ) return;

        const code = parsed.searchParams.get("code");
        if (!code || code.length < 4) return;

        const res  = await apiFetch("/api/auth/verify-code", {
          method:  "POST",
          headers: { "Content-Type": "application/json" },
          body:    JSON.stringify({ code: code.toUpperCase() }),
        });
        const data = await res.json() as {
          token?: string; telegramId?: string; error?: string;
        };
        if (data.token && data.telegramId) {
          loginNative(data.token, data.telegramId);
        }
      } catch { /* ignore parse / network errors */ }
    }

    // Dynamically import @capacitor/app to avoid breaking web/Telegram builds
    let cleanup: (() => void) | undefined;
    import("@capacitor/app").then(({ App }) => {
      // Check if app was opened directly via the deep link (cold start)
      App.getLaunchUrl()
        .then(result => { if (result?.url) handleUrl(result.url); })
        .catch(() => {});

      // Listen for deep links when app is already running (warm start)
      const promise = App.addListener("appUrlOpen", ({ url }) => handleUrl(url));
      cleanup = () => { promise.then(h => h.remove()).catch(() => {}); };
    }).catch(() => {});

    return () => { cleanup?.(); };
  }, [isNativeMode, isAuthenticated, loginNative]);

  if (isNativeMode && !isAuthenticated) {
    return <NativeLoginScreen />;
  }
  return <>{children}</>;
}

function App() {
  return (
    <ErrorBoundary>
      <QueryClientProvider client={queryClient}>
        <TooltipProvider>
          <TelegramProvider>
            <NativeAuthGate>
              <WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, "")}>
                <Router />
              </WouterRouter>
            </NativeAuthGate>
            <Toaster />
            <DevModelSwitcher />
          </TelegramProvider>
        </TooltipProvider>
      </QueryClientProvider>
    </ErrorBoundary>
  );
}

export default App;
